"""Tests for the NTSC-CRT Blender addon (real-time frame handler version).

Exercises addon registration, UI properties, helper functions, the toggle
operator, and the frame_change_post handler that processes frames in real-time.

Run inside Blender in background mode:
    NTSC_CRT_PATH=/path/to/NTSC-CRT/python \
    /path/to/blender --background --python test/test_addon.py

Requires test/test_input.mp4 (generated by test runner or manually).
"""

import os
import sys
import unittest

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_TEST_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_TEST_DIR, os.pardir))

_NTSC_CRT_PATH = os.environ.get("NTSC_CRT_PATH")
if not _NTSC_CRT_PATH:
    _NTSC_CRT_PATH = os.path.join(_REPO_ROOT, "python")

for _p in (_NTSC_CRT_PATH, os.path.join(_NTSC_CRT_PATH, "lib")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

_ADDON_DIR = os.path.join(_REPO_ROOT, "examples", "blender_addon")

import bpy
import importlib.util

# Force-load the addon module from the repo, not Blender's installed copy
_spec = importlib.util.spec_from_file_location(
    "ntsc_crt_addon", os.path.join(_ADDON_DIR, "main.py")
)
addon_module = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(addon_module)

TEST_VIDEO = os.path.join(_TEST_DIR, "test_input.mp4")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_registered():
    if not hasattr(bpy.types.Scene, "ntsc_crt"):
        addon_module.register()


def _clear_sequencer():
    """Remove all strips from the sequencer."""
    scene = bpy.context.scene
    if scene.sequence_editor is None:
        return
    _, strips = addon_module._get_strips(scene)
    for s in list(strips):
        strips.remove(s)


def _add_movie_strip(filepath, channel=1, frame_start=1):
    """Add a movie strip and make it active. Returns the strip."""
    scene = bpy.context.scene
    if scene.sequence_editor is None:
        scene.sequence_editor_create()
    _, strips = addon_module._get_strips(scene)
    strip = strips.new_movie(
        name="Test Video",
        filepath=filepath,
        channel=channel,
        frame_start=frame_start,
    )
    scene.sequence_editor.active_strip = strip
    return strip


def _reset_props():
    """Reset all addon properties to their defaults."""
    props = bpy.context.scene.ntsc_crt
    props.enabled = False
    props.mix_enabled = False
    props.mix_ratio = 50
    props.hue = 0
    props.brightness = 0
    props.contrast = 180
    props.saturation = 10
    props.black_point = 0
    props.white_point = 100
    props.scanlines = True
    props.blend = True
    props.v_fac = 0
    props.noise = 24
    props.strip_settings.clear()


def _disable_handler():
    """Ensure handler is removed and state is clean."""
    handler = addon_module._ntsc_frame_handler
    if handler in bpy.app.handlers.frame_change_post:
        bpy.app.handlers.frame_change_post.remove(handler)
    addon_module._HandlerState.release_all()


# ===================================================================
# Test: Registration
# ===================================================================

class TestAddonRegistration(unittest.TestCase):

    def test_register(self):
        addon_module.register()
        self.assertTrue(hasattr(bpy.types.Scene, "ntsc_crt"))

    def test_unregister_and_reregister(self):
        _ensure_registered()
        addon_module.unregister()
        self.assertFalse(hasattr(bpy.types.Scene, "ntsc_crt"))
        addon_module.register()
        self.assertTrue(hasattr(bpy.types.Scene, "ntsc_crt"))

    def test_unregister_removes_handler(self):
        _ensure_registered()
        # Manually add handler
        handler = addon_module._ntsc_frame_handler
        if handler not in bpy.app.handlers.frame_change_post:
            bpy.app.handlers.frame_change_post.append(handler)
        addon_module.unregister()
        self.assertNotIn(handler, bpy.app.handlers.frame_change_post)
        addon_module.register()


# ===================================================================
# Test: All Property Defaults
# ===================================================================

class TestPropertyDefaults(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        self.props = bpy.context.scene.ntsc_crt
        self.settings = addon_module._get_strip_settings(
            self.props, "test_strip")

    def test_enabled(self):
        self.assertFalse(self.props.enabled)

    def test_system(self):
        self.assertEqual(self.settings.system, "ntsc")

    def test_monitor_defaults(self):
        self.assertEqual(self.props.hue, 0)
        self.assertEqual(self.props.brightness, 0)
        self.assertEqual(self.props.contrast, 180)
        self.assertEqual(self.props.saturation, 10)
        self.assertEqual(self.props.black_point, 0)
        self.assertEqual(self.props.white_point, 100)

    def test_display_defaults(self):
        self.assertTrue(self.props.scanlines)
        self.assertTrue(self.props.blend)
        self.assertEqual(self.props.v_fac, 0)

    def test_signal_defaults(self):
        self.assertEqual(self.props.noise, 24)
        self.assertEqual(self.settings.artifact_hue, 0)
        self.assertEqual(self.settings.num_frames, 4)
        self.assertFalse(self.settings.progressive)
        self.assertFalse(self.settings.raw)
        self.assertTrue(self.settings.as_color)

    def test_offset_defaults(self):
        self.assertEqual(self.settings.xoffset, 0)
        self.assertEqual(self.settings.yoffset, 0)

    def test_vhs_defaults(self):
        self.assertFalse(self.settings.do_aberration)

    def test_mix_defaults(self):
        self.assertFalse(self.props.mix_enabled)
        self.assertEqual(self.props.mix_ratio, 50)

    def test_strip_settings_independent(self):
        """Two different strips get independent settings."""
        s1 = addon_module._get_strip_settings(self.props, "strip_1")
        s2 = addon_module._get_strip_settings(self.props, "strip_2")
        s1.artifact_hue = 42
        s2.artifact_hue = 90
        self.assertEqual(s1.artifact_hue, 42)
        self.assertEqual(s2.artifact_hue, 90)


# ===================================================================
# Test: Property Read/Write
# ===================================================================

class TestPropertyReadWrite(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        self.props = bpy.context.scene.ntsc_crt
        self.settings = addon_module._get_strip_settings(
            self.props, "test_strip")

    def test_enabled_toggle(self):
        self.props.enabled = True
        self.assertTrue(self.props.enabled)
        self.props.enabled = False
        self.assertFalse(self.props.enabled)

    def test_system_switch(self):
        self.settings.system = "ntscvhs"
        self.assertEqual(self.settings.system, "ntscvhs")
        self.settings.system = "ntsc"
        self.assertEqual(self.settings.system, "ntsc")

    def test_monitor_props(self):
        self.props.hue = -90
        self.props.brightness = 50
        self.props.contrast = 250
        self.props.saturation = 80
        self.props.black_point = -20
        self.props.white_point = 150
        self.assertEqual(self.props.hue, -90)
        self.assertEqual(self.props.brightness, 50)
        self.assertEqual(self.props.contrast, 250)
        self.assertEqual(self.props.saturation, 80)
        self.assertEqual(self.props.black_point, -20)
        self.assertEqual(self.props.white_point, 150)

    def test_display_props(self):
        self.props.scanlines = False
        self.props.blend = False
        self.props.v_fac = 42
        self.assertFalse(self.props.scanlines)
        self.assertFalse(self.props.blend)
        self.assertEqual(self.props.v_fac, 42)

    def test_signal_props(self):
        self.props.noise = 100
        self.settings.artifact_hue = 180
        self.settings.num_frames = 8
        self.settings.progressive = True
        self.settings.raw = True
        self.settings.as_color = False
        self.assertEqual(self.props.noise, 100)
        self.assertEqual(self.settings.artifact_hue, 180)
        self.assertEqual(self.settings.num_frames, 8)
        self.assertTrue(self.settings.progressive)
        self.assertTrue(self.settings.raw)
        self.assertFalse(self.settings.as_color)

    def test_offset_props(self):
        self.settings.xoffset = 50
        self.settings.yoffset = -30
        self.assertEqual(self.settings.xoffset, 50)
        self.assertEqual(self.settings.yoffset, -30)

    def test_vhs_props(self):
        self.settings.do_aberration = True
        self.assertTrue(self.settings.do_aberration)

    def test_mix_props(self):
        self.props.mix_enabled = True
        self.assertTrue(self.props.mix_enabled)
        self.props.mix_enabled = False
        self.assertFalse(self.props.mix_enabled)
        self.props.mix_ratio = 0
        self.assertEqual(self.props.mix_ratio, 0)
        self.props.mix_ratio = 100
        self.assertEqual(self.props.mix_ratio, 100)

    def test_per_strip_read_write(self):
        """Per-strip settings are readable and writable."""
        self.settings.system = "ntscvhs"
        self.assertEqual(self.settings.system, "ntscvhs")
        self.settings.artifact_hue = 180
        self.assertEqual(self.settings.artifact_hue, 180)
        self.settings.xoffset = 50
        self.assertEqual(self.settings.xoffset, 50)
        self.settings.do_aberration = True
        self.assertTrue(self.settings.do_aberration)


# ===================================================================
# Test: Helper Functions
# ===================================================================

class TestHelpers(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def test_get_strips_empty(self):
        _clear_sequencer()
        sed, strips = addon_module._get_strips(bpy.context.scene)
        if sed is not None:
            self.assertEqual(len(list(strips)), 0)

    def test_active_movie_strip_none(self):
        _clear_sequencer()
        result = addon_module._active_movie_strip(bpy.context)
        self.assertIsNone(result)

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_active_movie_strip_found(self):
        _clear_sequencer()
        _add_movie_strip(TEST_VIDEO)
        result = addon_module._active_movie_strip(bpy.context)
        self.assertIsNotNone(result)
        self.assertEqual(result.type, "MOVIE")
        _clear_sequencer()

    def test_get_selected_movie_strips_none(self):
        _clear_sequencer()
        a, b = addon_module._get_selected_movie_strips(bpy.context)
        self.assertIsNone(a)
        self.assertIsNone(b)

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_get_selected_movie_strips_one(self):
        _clear_sequencer()
        _add_movie_strip(TEST_VIDEO)
        a, b = addon_module._get_selected_movie_strips(bpy.context)
        self.assertIsNotNone(a)
        self.assertIsNone(b)
        _clear_sequencer()

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_get_selected_movie_strips_two(self):
        _clear_sequencer()
        s1 = _add_movie_strip(TEST_VIDEO, channel=1)
        s2 = _add_movie_strip(TEST_VIDEO, channel=2)
        s1.select = True
        s2.select = True
        # Active = s2 (last added), so s1 should be strip_b
        a, b = addon_module._get_selected_movie_strips(bpy.context)
        self.assertIsNotNone(a)
        self.assertIsNotNone(b)
        self.assertNotEqual(a, b)
        _clear_sequencer()


# ===================================================================
# Test: Mix Helper Functions
# ===================================================================

class TestMixHelpers(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def test_get_strip_settings_creates_entry(self):
        """_get_strip_settings creates a new entry for an unknown strip."""
        props = bpy.context.scene.ntsc_crt
        _reset_props()
        settings = addon_module._get_strip_settings(props, "new_strip")
        self.assertEqual(settings.strip_name, "new_strip")
        self.assertEqual(settings.system, "ntsc")  # default

    def test_get_strip_settings_returns_existing(self):
        """_get_strip_settings returns the same entry for the same strip."""
        props = bpy.context.scene.ntsc_crt
        _reset_props()
        s1 = addon_module._get_strip_settings(props, "test_strip")
        s1.artifact_hue = 42
        s2 = addon_module._get_strip_settings(props, "test_strip")
        self.assertEqual(s2.artifact_hue, 42)

    def test_mix_and_normalize_equal_ratio(self):
        import numpy as np
        # Two simple signals
        sig_a = np.full((262, 910), 80, dtype=np.int8)
        sig_b = np.full((262, 910), 40, dtype=np.int8)
        mixed = addon_module._mix_and_normalize(sig_a, sig_b, 50)
        self.assertEqual(mixed.dtype, np.int8)
        self.assertEqual(mixed.shape, (262, 910))
        # Normalized: peak should be close to max(80, 40) = 80
        self.assertGreater(int(mixed.max()), 70)

    def test_mix_and_normalize_all_a(self):
        import numpy as np
        sig_a = np.full((262, 910), 80, dtype=np.int8)
        sig_b = np.full((262, 910), 40, dtype=np.int8)
        mixed = addon_module._mix_and_normalize(sig_a, sig_b, 0)
        # ratio=0 means all A; peak ≈ 80
        self.assertAlmostEqual(int(mixed.max()), 80, delta=2)

    def test_mix_and_normalize_all_b(self):
        import numpy as np
        sig_a = np.full((262, 910), 80, dtype=np.int8)
        sig_b = np.full((262, 910), 40, dtype=np.int8)
        mixed = addon_module._mix_and_normalize(sig_a, sig_b, 100)
        # ratio=100 means all B; normalized peak ≈ 80 (scaled up from 40)
        self.assertGreater(int(mixed.max()), 70)

    def test_mix_and_normalize_preserves_sync(self):
        import numpy as np
        sig_a = np.full((262, 910), 80, dtype=np.int8)
        sig_b = np.full((262, 910), 80, dtype=np.int8)
        # Set some sync values (negative IRE)
        sig_a[:, :50] = -40
        sig_b[:, :50] = -40
        mixed = addon_module._mix_and_normalize(sig_a, sig_b, 50)
        # Sync region should remain negative
        self.assertTrue((mixed[:, :50] < 0).all())

    def test_mix_and_normalize_shape_preserved(self):
        import numpy as np
        sig_a = np.zeros((262, 910), dtype=np.int8)
        sig_b = np.zeros((262, 910), dtype=np.int8)
        mixed = addon_module._mix_and_normalize(sig_a, sig_b, 50)
        self.assertEqual(mixed.shape, (262, 910))
        self.assertEqual(mixed.dtype, np.int8)


# ===================================================================
# Test: HandlerState
# ===================================================================

class TestHandlerState(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        addon_module._HandlerState.release_all()

    def tearDown(self):
        addon_module._HandlerState.release_all()

    def test_get_crt_slot_creates_instance(self):
        crt = addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        self.assertIsNotNone(crt)
        self.assertEqual(crt.system, "ntsc")
        self.assertEqual(crt.out_w, 320)
        self.assertEqual(crt.out_h, 240)

    def test_get_crt_slot_caches_instance(self):
        crt1 = addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        crt2 = addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        self.assertIs(crt1, crt2)

    def test_get_crt_slot_recreates_on_system_change(self):
        crt1 = addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        crt2 = addon_module._HandlerState.get_crt_slot("a", "ntscvhs", 320, 240)
        self.assertIsNot(crt1, crt2)
        self.assertEqual(crt2.system, "ntscvhs")

    def test_get_crt_slot_recreates_on_resolution_change(self):
        crt1 = addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        crt2 = addon_module._HandlerState.get_crt_slot("a", "ntsc", 640, 480)
        self.assertIsNot(crt1, crt2)

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_get_cap_opens_video(self):
        cap = addon_module._HandlerState.get_cap(TEST_VIDEO)
        self.assertIsNotNone(cap)
        self.assertTrue(cap.isOpened())

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_get_cap_caches(self):
        cap1 = addon_module._HandlerState.get_cap(TEST_VIDEO)
        cap2 = addon_module._HandlerState.get_cap(TEST_VIDEO)
        self.assertIs(cap1, cap2)

    def test_release_all(self):
        addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        addon_module._HandlerState.get_crt_slot("b", "ntscvhs", 320, 240)
        addon_module._HandlerState.release_all()
        self.assertEqual(len(addon_module._HandlerState._crts), 0)
        self.assertEqual(len(addon_module._HandlerState.caps), 0)

    def test_get_crt_slot_b_creates_instance(self):
        crt_b = addon_module._HandlerState.get_crt_slot("b", "ntsc", 320, 240)
        self.assertIsNotNone(crt_b)
        self.assertEqual(crt_b.system, "ntsc")

    def test_get_crt_slot_b_caches(self):
        c1 = addon_module._HandlerState.get_crt_slot("b", "ntsc", 320, 240)
        c2 = addon_module._HandlerState.get_crt_slot("b", "ntsc", 320, 240)
        self.assertIs(c1, c2)

    def test_slots_a_and_b_independent(self):
        crt_a = addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        crt_b = addon_module._HandlerState.get_crt_slot("b", "ntsc", 320, 240)
        self.assertIsNot(crt_a, crt_b)

    def test_get_crt_slot_b_recreates_on_system_change(self):
        c1 = addon_module._HandlerState.get_crt_slot("b", "ntsc", 320, 240)
        c2 = addon_module._HandlerState.get_crt_slot("b", "ntscvhs", 320, 240)
        self.assertIsNot(c1, c2)
        self.assertEqual(c2.system, "ntscvhs")

    def test_get_or_create_image(self):
        img = addon_module._HandlerState.get_or_create_image(320, 240)
        self.assertIsNotNone(img)
        self.assertEqual(img.size[0], 320)
        self.assertEqual(img.size[1], 240)
        self.assertEqual(img.name, addon_module._HandlerState.preview_name)
        # Cleanup
        bpy.data.images.remove(img)

    def test_get_or_create_image_recreates_on_size_change(self):
        img1 = addon_module._HandlerState.get_or_create_image(320, 240)
        img2 = addon_module._HandlerState.get_or_create_image(640, 480)
        self.assertEqual(img2.size[0], 640)
        self.assertEqual(img2.size[1], 480)
        # Old image should have been removed
        self.assertEqual(
            len([i for i in bpy.data.images if i.name == addon_module._HandlerState.preview_name]),
            1,
        )
        bpy.data.images.remove(img2)


# ===================================================================
# Test: Toggle Operator
# ===================================================================

class TestToggleOperator(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        _disable_handler()

    def tearDown(self):
        _disable_handler()
        _reset_props()

    def test_toggle_on(self):
        result = bpy.ops.sequencer.ntsc_toggle()
        self.assertIn("FINISHED", result)
        self.assertTrue(bpy.context.scene.ntsc_crt.enabled)
        self.assertIn(
            addon_module._ntsc_frame_handler,
            bpy.app.handlers.frame_change_post,
        )

    def test_toggle_off(self):
        # Enable first
        bpy.ops.sequencer.ntsc_toggle()
        # Disable
        result = bpy.ops.sequencer.ntsc_toggle()
        self.assertIn("FINISHED", result)
        self.assertFalse(bpy.context.scene.ntsc_crt.enabled)
        self.assertNotIn(
            addon_module._ntsc_frame_handler,
            bpy.app.handlers.frame_change_post,
        )

    def test_toggle_releases_state_on_disable(self):
        # Enable → create some cache
        addon_module._HandlerState.get_crt_slot("a", "ntsc", 320, 240)
        bpy.context.scene.ntsc_crt.enabled = True
        if addon_module._ntsc_frame_handler not in bpy.app.handlers.frame_change_post:
            bpy.app.handlers.frame_change_post.append(addon_module._ntsc_frame_handler)
        # Disable via operator
        bpy.ops.sequencer.ntsc_toggle()
        self.assertEqual(len(addon_module._HandlerState._crts), 0)


# ===================================================================
# Test: Frame Handler (NTSC)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestFrameHandlerNTSC(unittest.TestCase):
    """Test the frame_change_post handler processes frames correctly."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.strip = _add_movie_strip(TEST_VIDEO)
        self.settings = addon_module._get_strip_settings(
            self.props, self.strip.name)
        self.settings.num_frames = 1  # fast

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        # Remove preview image if it exists
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def _enable_and_process(self):
        """Enable handler and process current frame."""
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)

    def test_handler_does_nothing_when_disabled(self):
        self.props.enabled = False
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_handler_creates_preview_image(self):
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)
        self.assertGreater(img.size[0], 0)
        self.assertGreater(img.size[1], 0)

    def test_handler_preview_image_size_matches_video(self):
        import cv2
        cap = cv2.VideoCapture(TEST_VIDEO)
        expected_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        expected_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()

        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertEqual(img.size[0], expected_w)
        self.assertEqual(img.size[1], expected_h)

    def test_handler_preview_has_nonzero_pixels(self):
        import numpy as np
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels)
        self.assertGreater(np.max(pixels), 0.0)

    def test_handler_processes_different_frames(self):
        import numpy as np
        self.props.enabled = True

        # Process frame 1
        bpy.context.scene.frame_set(1)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels_1 = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_1)

        # Process frame 30
        bpy.context.scene.frame_set(30)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        pixels_30 = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_30)

        # They should be different (CRT noise if nothing else)
        self.assertFalse(np.array_equal(pixels_1, pixels_30))

    def test_handler_respects_custom_settings(self):
        import numpy as np
        self.props.enabled = True

        # Default settings
        bpy.context.scene.frame_set(1)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels_default = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_default)

        # Change contrast significantly
        self.props.contrast = 500
        # Invalidate CRT cache to pick up new settings
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        pixels_high = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_high)

        self.assertFalse(np.array_equal(pixels_default, pixels_high))

    def test_handler_skips_out_of_range_frame(self):
        self.props.enabled = True
        # Move to a frame outside the strip range
        bpy.context.scene.frame_set(9999)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_handler_no_strip(self):
        _clear_sequencer()
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_monochrome(self):
        self.settings.as_color = False
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_progressive(self):
        self.settings.progressive = True
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_no_scanlines_no_blend(self):
        self.props.scanlines = False
        self.props.blend = False
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_high_noise(self):
        self.props.noise = 200
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_offsets(self):
        self.settings.xoffset = 20
        self.settings.yoffset = -10
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)


# ===================================================================
# Test: Frame Handler (VHS)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestFrameHandlerVHS(unittest.TestCase):
    """Test the handler with ntscvhs system."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.strip = _add_movie_strip(TEST_VIDEO)
        self.settings = addon_module._get_strip_settings(
            self.props, self.strip.name)
        self.settings.system = "ntscvhs"
        self.settings.num_frames = 1

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def test_vhs_basic(self):
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_vhs_with_aberration(self):
        self.props.enabled = True
        self.settings.do_aberration = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_vhs_cache_system(self):
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        crt = addon_module._HandlerState._crts.get("a")
        self.assertIsNotNone(crt)
        self.assertEqual(crt.system, "ntscvhs")


# ===================================================================
# Test: Mix Toggle Operator
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestMixToggleOperator(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def test_mix_toggle_fails_no_strips(self):
        with self.assertRaises(RuntimeError):
            bpy.ops.sequencer.ntsc_mix_toggle()
        self.assertFalse(bpy.context.scene.ntsc_crt.mix_enabled)

    def test_mix_toggle_fails_one_strip(self):
        _add_movie_strip(TEST_VIDEO, channel=1)
        with self.assertRaises(RuntimeError):
            bpy.ops.sequencer.ntsc_mix_toggle()
        self.assertFalse(bpy.context.scene.ntsc_crt.mix_enabled)

    def test_mix_toggle_on_two_strips(self):
        s1 = _add_movie_strip(TEST_VIDEO, channel=1)
        s2 = _add_movie_strip(TEST_VIDEO, channel=2)
        s1.select = True
        s2.select = True
        result = bpy.ops.sequencer.ntsc_mix_toggle()
        self.assertIn("FINISHED", result)
        self.assertTrue(bpy.context.scene.ntsc_crt.mix_enabled)
        self.assertIn(
            addon_module._ntsc_frame_handler,
            bpy.app.handlers.frame_change_post,
        )

    def test_mix_toggle_off(self):
        s1 = _add_movie_strip(TEST_VIDEO, channel=1)
        s2 = _add_movie_strip(TEST_VIDEO, channel=2)
        s1.select = True
        s2.select = True
        bpy.ops.sequencer.ntsc_mix_toggle()  # enable
        result = bpy.ops.sequencer.ntsc_mix_toggle()  # disable
        self.assertIn("FINISHED", result)
        self.assertFalse(bpy.context.scene.ntsc_crt.mix_enabled)

    def test_mix_toggle_off_keeps_handler_when_preview_enabled(self):
        s1 = _add_movie_strip(TEST_VIDEO, channel=1)
        s2 = _add_movie_strip(TEST_VIDEO, channel=2)
        s1.select = True
        s2.select = True
        # Enable single-strip preview first
        bpy.ops.sequencer.ntsc_toggle()
        # Enable mix
        bpy.ops.sequencer.ntsc_mix_toggle()
        # Disable mix — handler should stay because single preview is still on
        bpy.ops.sequencer.ntsc_mix_toggle()
        self.assertIn(
            addon_module._ntsc_frame_handler,
            bpy.app.handlers.frame_change_post,
        )


# ===================================================================
# Test: Mix Frame Handler
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestMixFrameHandler(unittest.TestCase):
    """Test the frame handler in signal-mix mode."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.strip_a = _add_movie_strip(TEST_VIDEO, channel=1)
        self.strip_b = _add_movie_strip(TEST_VIDEO, channel=2)
        self.strip_a.select = True
        self.strip_b.select = True
        # Ensure strip_a is active so the handler treats it as A
        bpy.context.scene.sequence_editor.active_strip = self.strip_a
        self.settings_a = addon_module._get_strip_settings(
            self.props, self.strip_a.name)
        self.settings_b = addon_module._get_strip_settings(
            self.props, self.strip_b.name)
        self.settings_a.num_frames = 1
        self.settings_b.num_frames = 1

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def _enable_mix_and_process(self):
        self.props.mix_enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)

    def test_mix_handler_creates_preview(self):
        self._enable_mix_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)
        self.assertGreater(img.size[0], 0)
        self.assertGreater(img.size[1], 0)

    def test_mix_handler_has_nonzero_pixels(self):
        import numpy as np
        self._enable_mix_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels)
        self.assertGreater(np.max(pixels), 0.0)

    def test_mix_ratio_0_vs_100(self):
        """Ratio extremes should produce different results when mixed with
        a brightness-shifted version of the same video."""
        import numpy as np

        self.props.mix_enabled = True

        # Ratio = 0 (all A)
        self.props.mix_ratio = 0
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        p0 = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(p0)

        # Ratio = 100 (all B)
        self.props.mix_ratio = 100
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        p100 = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(p100)

        # With same video the signals are identical so after normalization
        # the outputs should be very similar — just verify both are valid
        self.assertGreater(np.max(p0), 0.0)
        self.assertGreater(np.max(p100), 0.0)

    def test_mix_does_nothing_when_disabled(self):
        self.props.mix_enabled = False
        self.props.enabled = False
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_mix_no_second_strip_produces_nothing(self):
        """With mix_enabled but only one strip, no output is produced."""
        _clear_sequencer()
        strip = _add_movie_strip(TEST_VIDEO, channel=1)
        settings = addon_module._get_strip_settings(self.props, strip.name)
        settings.num_frames = 1
        self.props.mix_enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_mix_with_custom_settings(self):
        import numpy as np
        self.props.mix_enabled = True
        self.props.contrast = 300
        self.props.noise = 0
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)
        pixels = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels)
        self.assertGreater(np.max(pixels), 0.0)

    def test_mix_with_independent_b_settings(self):
        """Strip B uses its own system & knobs, independent of A."""
        import numpy as np
        self.props.mix_enabled = True
        self.props.mix_ratio = 50
        # B = ntscvhs with different artifact_hue
        self.settings_b.system = "ntscvhs"
        self.settings_b.artifact_hue = 180
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)
        pixels = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels)
        self.assertGreater(np.max(pixels), 0.0)
        # Verify CRT B was created with ntscvhs system
        crt_b = addon_module._HandlerState._crts.get("b")
        self.assertIsNotNone(crt_b)
        self.assertEqual(crt_b.system, "ntscvhs")
        # Verify CRT A is still ntsc
        crt_a = addon_module._HandlerState._crts.get("a")
        self.assertIsNotNone(crt_a)
        self.assertEqual(crt_a.system, "ntsc")

    def test_mix_handler_skips_out_of_range(self):
        self.props.mix_enabled = True
        bpy.context.scene.frame_set(9999)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_mix_b_knobs_affect_output(self):
        """Changing strip B's artifact_hue produces different output."""
        import numpy as np
        self.props.mix_enabled = True
        self.props.mix_ratio = 100  # all B

        # Default B settings
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        p_default = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(p_default)

        # Change B artifact_hue drastically
        self.settings_b.artifact_hue = 180
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        p_changed = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(p_changed)

        self.assertFalse(np.array_equal(p_default, p_changed),
                         "Changing strip B artifact_hue should affect mix output")


# ===================================================================
# Test: Reset Operator covers mix
# ===================================================================

class TestResetOperatorMix(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()

    def test_reset_restores_mix_ratio(self):
        props = bpy.context.scene.ntsc_crt
        props.mix_ratio = 75
        bpy.ops.sequencer.ntsc_reset()
        self.assertEqual(bpy.context.scene.ntsc_crt.mix_ratio, 50)

    def test_reset_clears_strip_settings(self):
        props = bpy.context.scene.ntsc_crt
        addon_module._get_strip_settings(props, "strip_a")
        addon_module._get_strip_settings(props, "strip_b")
        self.assertGreater(len(props.strip_settings), 0)
        bpy.ops.sequencer.ntsc_reset()
        self.assertEqual(len(bpy.context.scene.ntsc_crt.strip_settings), 0)

    def test_reset_restores_global_monitor(self):
        props = bpy.context.scene.ntsc_crt
        props.hue = 90
        props.brightness = 50
        props.contrast = 400
        props.noise = 100
        bpy.ops.sequencer.ntsc_reset()
        props = bpy.context.scene.ntsc_crt
        self.assertEqual(props.hue, 0)
        self.assertEqual(props.brightness, 0)
        self.assertEqual(props.contrast, 180)
        self.assertEqual(props.noise, 24)


# ===================================================================
# Test: Refresh Operator
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestRefreshOperator(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.props.enabled = True
        strip = _add_movie_strip(TEST_VIDEO)
        settings = addon_module._get_strip_settings(self.props, strip.name)
        settings.num_frames = 1

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def test_refresh_processes_frame(self):
        result = bpy.ops.sequencer.ntsc_refresh()
        self.assertIn("FINISHED", result)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)


# ===================================================================
# Test: HandlerState multi-capture (dict-based caps)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestHandlerStateMultiCap(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        addon_module._HandlerState.release_all()

    def tearDown(self):
        addon_module._HandlerState.release_all()

    def test_caps_is_dict(self):
        self.assertIsInstance(addon_module._HandlerState.caps, dict)

    def test_get_cap_populates_dict(self):
        cap = addon_module._HandlerState.get_cap(TEST_VIDEO)
        self.assertIn(TEST_VIDEO, addon_module._HandlerState.caps)
        self.assertTrue(cap.isOpened())

    def test_release_cap_by_path(self):
        addon_module._HandlerState.get_cap(TEST_VIDEO)
        addon_module._HandlerState.release_cap(TEST_VIDEO)
        self.assertNotIn(TEST_VIDEO, addon_module._HandlerState.caps)

    def test_release_all_clears_caps(self):
        addon_module._HandlerState.get_cap(TEST_VIDEO)
        addon_module._HandlerState.release_all()
        self.assertEqual(len(addon_module._HandlerState.caps), 0)


# ===================================================================
# Entry point
# ===================================================================

if __name__ == "__main__":
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = [argv[0]]

    unittest.main(argv=["test_addon"] + argv[1:], exit=False)
