"""Tests for the NTSC-CRT Blender addon (real-time frame handler version).

Exercises addon registration, UI properties, helper functions, the toggle
operator, and the frame_change_post handler that processes frames in real-time.

Run inside Blender in background mode:
    NTSC_CRT_PATH=/path/to/NTSC-CRT/python \
    /path/to/blender --background --python test/test_addon.py

Requires test/test_input.mp4 (generated by test runner or manually).
"""

import os
import sys
import unittest

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_TEST_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_TEST_DIR, os.pardir))

_NTSC_CRT_PATH = os.environ.get("NTSC_CRT_PATH")
if not _NTSC_CRT_PATH:
    _NTSC_CRT_PATH = os.path.join(_REPO_ROOT, "python")

for _p in (_NTSC_CRT_PATH, os.path.join(_NTSC_CRT_PATH, "lib")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

_ADDON_DIR = os.path.join(_REPO_ROOT, "examples", "blender_addon")

import bpy
import importlib.util

# Force-load the addon module from the repo, not Blender's installed copy
_spec = importlib.util.spec_from_file_location(
    "ntsc_crt_addon", os.path.join(_ADDON_DIR, "main.py")
)
addon_module = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(addon_module)

TEST_VIDEO = os.path.join(_TEST_DIR, "test_input.mp4")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_registered():
    if not hasattr(bpy.types.Scene, "ntsc_crt"):
        addon_module.register()


def _clear_sequencer():
    """Remove all strips from the sequencer."""
    scene = bpy.context.scene
    if scene.sequence_editor is None:
        return
    _, strips = addon_module._get_strips(scene)
    for s in list(strips):
        strips.remove(s)


def _add_movie_strip(filepath, channel=1, frame_start=1):
    """Add a movie strip and make it active. Returns the strip."""
    scene = bpy.context.scene
    if scene.sequence_editor is None:
        scene.sequence_editor_create()
    _, strips = addon_module._get_strips(scene)
    strip = strips.new_movie(
        name="Test Video",
        filepath=filepath,
        channel=channel,
        frame_start=frame_start,
    )
    scene.sequence_editor.active_strip = strip
    return strip


def _reset_props():
    """Reset all addon properties to their defaults."""
    props = bpy.context.scene.ntsc_crt
    props.enabled = False
    props.system = "ntsc"
    props.hue = 0
    props.brightness = 0
    props.contrast = 180
    props.saturation = 10
    props.black_point = 0
    props.white_point = 100
    props.scanlines = True
    props.blend = True
    props.v_fac = 0
    props.noise = 24
    props.artifact_hue = 0
    props.num_frames = 4
    props.progressive = False
    props.raw = False
    props.as_color = True
    props.xoffset = 0
    props.yoffset = 0
    props.do_aberration = False


def _disable_handler():
    """Ensure handler is removed and state is clean."""
    handler = addon_module._ntsc_frame_handler
    if handler in bpy.app.handlers.frame_change_post:
        bpy.app.handlers.frame_change_post.remove(handler)
    addon_module._HandlerState.release_all()


# ===================================================================
# Test: Registration
# ===================================================================

class TestAddonRegistration(unittest.TestCase):

    def test_register(self):
        addon_module.register()
        self.assertTrue(hasattr(bpy.types.Scene, "ntsc_crt"))

    def test_unregister_and_reregister(self):
        _ensure_registered()
        addon_module.unregister()
        self.assertFalse(hasattr(bpy.types.Scene, "ntsc_crt"))
        addon_module.register()
        self.assertTrue(hasattr(bpy.types.Scene, "ntsc_crt"))

    def test_unregister_removes_handler(self):
        _ensure_registered()
        # Manually add handler
        handler = addon_module._ntsc_frame_handler
        if handler not in bpy.app.handlers.frame_change_post:
            bpy.app.handlers.frame_change_post.append(handler)
        addon_module.unregister()
        self.assertNotIn(handler, bpy.app.handlers.frame_change_post)
        addon_module.register()


# ===================================================================
# Test: All Property Defaults
# ===================================================================

class TestPropertyDefaults(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        self.props = bpy.context.scene.ntsc_crt

    def test_enabled(self):
        self.assertFalse(self.props.enabled)

    def test_system(self):
        self.assertEqual(self.props.system, "ntsc")

    def test_monitor_defaults(self):
        self.assertEqual(self.props.hue, 0)
        self.assertEqual(self.props.brightness, 0)
        self.assertEqual(self.props.contrast, 180)
        self.assertEqual(self.props.saturation, 10)
        self.assertEqual(self.props.black_point, 0)
        self.assertEqual(self.props.white_point, 100)

    def test_display_defaults(self):
        self.assertTrue(self.props.scanlines)
        self.assertTrue(self.props.blend)
        self.assertEqual(self.props.v_fac, 0)

    def test_signal_defaults(self):
        self.assertEqual(self.props.noise, 24)
        self.assertEqual(self.props.artifact_hue, 0)
        self.assertEqual(self.props.num_frames, 4)
        self.assertFalse(self.props.progressive)
        self.assertFalse(self.props.raw)
        self.assertTrue(self.props.as_color)

    def test_offset_defaults(self):
        self.assertEqual(self.props.xoffset, 0)
        self.assertEqual(self.props.yoffset, 0)

    def test_vhs_defaults(self):
        self.assertFalse(self.props.do_aberration)


# ===================================================================
# Test: Property Read/Write
# ===================================================================

class TestPropertyReadWrite(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        self.props = bpy.context.scene.ntsc_crt

    def test_enabled_toggle(self):
        self.props.enabled = True
        self.assertTrue(self.props.enabled)
        self.props.enabled = False
        self.assertFalse(self.props.enabled)

    def test_system_switch(self):
        self.props.system = "ntscvhs"
        self.assertEqual(self.props.system, "ntscvhs")
        self.props.system = "ntsc"
        self.assertEqual(self.props.system, "ntsc")

    def test_monitor_props(self):
        self.props.hue = -90
        self.props.brightness = 50
        self.props.contrast = 250
        self.props.saturation = 80
        self.props.black_point = -20
        self.props.white_point = 150
        self.assertEqual(self.props.hue, -90)
        self.assertEqual(self.props.brightness, 50)
        self.assertEqual(self.props.contrast, 250)
        self.assertEqual(self.props.saturation, 80)
        self.assertEqual(self.props.black_point, -20)
        self.assertEqual(self.props.white_point, 150)

    def test_display_props(self):
        self.props.scanlines = False
        self.props.blend = False
        self.props.v_fac = 42
        self.assertFalse(self.props.scanlines)
        self.assertFalse(self.props.blend)
        self.assertEqual(self.props.v_fac, 42)

    def test_signal_props(self):
        self.props.noise = 100
        self.props.artifact_hue = 180
        self.props.num_frames = 8
        self.props.progressive = True
        self.props.raw = True
        self.props.as_color = False
        self.assertEqual(self.props.noise, 100)
        self.assertEqual(self.props.artifact_hue, 180)
        self.assertEqual(self.props.num_frames, 8)
        self.assertTrue(self.props.progressive)
        self.assertTrue(self.props.raw)
        self.assertFalse(self.props.as_color)

    def test_offset_props(self):
        self.props.xoffset = 50
        self.props.yoffset = -30
        self.assertEqual(self.props.xoffset, 50)
        self.assertEqual(self.props.yoffset, -30)

    def test_vhs_props(self):
        self.props.do_aberration = True
        self.assertTrue(self.props.do_aberration)


# ===================================================================
# Test: Helper Functions
# ===================================================================

class TestHelpers(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def test_get_strips_empty(self):
        _clear_sequencer()
        sed, strips = addon_module._get_strips(bpy.context.scene)
        if sed is not None:
            self.assertEqual(len(list(strips)), 0)

    def test_active_movie_strip_none(self):
        _clear_sequencer()
        result = addon_module._active_movie_strip(bpy.context)
        self.assertIsNone(result)

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_active_movie_strip_found(self):
        _clear_sequencer()
        _add_movie_strip(TEST_VIDEO)
        result = addon_module._active_movie_strip(bpy.context)
        self.assertIsNotNone(result)
        self.assertEqual(result.type, "MOVIE")
        _clear_sequencer()


# ===================================================================
# Test: HandlerState
# ===================================================================

class TestHandlerState(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        addon_module._HandlerState.release_all()

    def tearDown(self):
        addon_module._HandlerState.release_all()

    def test_get_crt_creates_instance(self):
        crt = addon_module._HandlerState.get_crt("ntsc", 320, 240)
        self.assertIsNotNone(crt)
        self.assertEqual(addon_module._HandlerState.crt_system, "ntsc")
        self.assertEqual(addon_module._HandlerState.crt_w, 320)
        self.assertEqual(addon_module._HandlerState.crt_h, 240)

    def test_get_crt_caches_instance(self):
        crt1 = addon_module._HandlerState.get_crt("ntsc", 320, 240)
        crt2 = addon_module._HandlerState.get_crt("ntsc", 320, 240)
        self.assertIs(crt1, crt2)

    def test_get_crt_recreates_on_system_change(self):
        crt1 = addon_module._HandlerState.get_crt("ntsc", 320, 240)
        crt2 = addon_module._HandlerState.get_crt("ntscvhs", 320, 240)
        self.assertIsNot(crt1, crt2)
        self.assertEqual(addon_module._HandlerState.crt_system, "ntscvhs")

    def test_get_crt_recreates_on_resolution_change(self):
        crt1 = addon_module._HandlerState.get_crt("ntsc", 320, 240)
        crt2 = addon_module._HandlerState.get_crt("ntsc", 640, 480)
        self.assertIsNot(crt1, crt2)

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_get_cap_opens_video(self):
        cap = addon_module._HandlerState.get_cap(TEST_VIDEO)
        self.assertIsNotNone(cap)
        self.assertTrue(cap.isOpened())

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_get_cap_caches(self):
        cap1 = addon_module._HandlerState.get_cap(TEST_VIDEO)
        cap2 = addon_module._HandlerState.get_cap(TEST_VIDEO)
        self.assertIs(cap1, cap2)

    def test_release_all(self):
        addon_module._HandlerState.get_crt("ntsc", 320, 240)
        addon_module._HandlerState.release_all()
        self.assertIsNone(addon_module._HandlerState.crt)
        self.assertIsNone(addon_module._HandlerState.cap)

    def test_get_or_create_image(self):
        img = addon_module._HandlerState.get_or_create_image(320, 240)
        self.assertIsNotNone(img)
        self.assertEqual(img.size[0], 320)
        self.assertEqual(img.size[1], 240)
        self.assertEqual(img.name, addon_module._HandlerState.preview_name)
        # Cleanup
        bpy.data.images.remove(img)

    def test_get_or_create_image_recreates_on_size_change(self):
        img1 = addon_module._HandlerState.get_or_create_image(320, 240)
        img2 = addon_module._HandlerState.get_or_create_image(640, 480)
        self.assertEqual(img2.size[0], 640)
        self.assertEqual(img2.size[1], 480)
        # Old image should have been removed
        self.assertEqual(
            len([i for i in bpy.data.images if i.name == addon_module._HandlerState.preview_name]),
            1,
        )
        bpy.data.images.remove(img2)


# ===================================================================
# Test: Toggle Operator
# ===================================================================

class TestToggleOperator(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        _disable_handler()

    def tearDown(self):
        _disable_handler()
        _reset_props()

    def test_toggle_on(self):
        result = bpy.ops.sequencer.ntsc_toggle()
        self.assertIn("FINISHED", result)
        self.assertTrue(bpy.context.scene.ntsc_crt.enabled)
        self.assertIn(
            addon_module._ntsc_frame_handler,
            bpy.app.handlers.frame_change_post,
        )

    def test_toggle_off(self):
        # Enable first
        bpy.ops.sequencer.ntsc_toggle()
        # Disable
        result = bpy.ops.sequencer.ntsc_toggle()
        self.assertIn("FINISHED", result)
        self.assertFalse(bpy.context.scene.ntsc_crt.enabled)
        self.assertNotIn(
            addon_module._ntsc_frame_handler,
            bpy.app.handlers.frame_change_post,
        )

    def test_toggle_releases_state_on_disable(self):
        # Enable → create some cache
        addon_module._HandlerState.get_crt("ntsc", 320, 240)
        bpy.context.scene.ntsc_crt.enabled = True
        if addon_module._ntsc_frame_handler not in bpy.app.handlers.frame_change_post:
            bpy.app.handlers.frame_change_post.append(addon_module._ntsc_frame_handler)
        # Disable via operator
        bpy.ops.sequencer.ntsc_toggle()
        self.assertIsNone(addon_module._HandlerState.crt)


# ===================================================================
# Test: Frame Handler (NTSC)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestFrameHandlerNTSC(unittest.TestCase):
    """Test the frame_change_post handler processes frames correctly."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.props.num_frames = 1  # fast
        self.strip = _add_movie_strip(TEST_VIDEO)

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        # Remove preview image if it exists
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def _enable_and_process(self):
        """Enable handler and process current frame."""
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)

    def test_handler_does_nothing_when_disabled(self):
        self.props.enabled = False
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_handler_creates_preview_image(self):
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)
        self.assertGreater(img.size[0], 0)
        self.assertGreater(img.size[1], 0)

    def test_handler_preview_image_size_matches_video(self):
        import cv2
        cap = cv2.VideoCapture(TEST_VIDEO)
        expected_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        expected_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()

        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertEqual(img.size[0], expected_w)
        self.assertEqual(img.size[1], expected_h)

    def test_handler_preview_has_nonzero_pixels(self):
        import numpy as np
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels)
        self.assertGreater(np.max(pixels), 0.0)

    def test_handler_processes_different_frames(self):
        import numpy as np
        self.props.enabled = True

        # Process frame 1
        bpy.context.scene.frame_set(1)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels_1 = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_1)

        # Process frame 30
        bpy.context.scene.frame_set(30)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        pixels_30 = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_30)

        # They should be different (CRT noise if nothing else)
        self.assertFalse(np.array_equal(pixels_1, pixels_30))

    def test_handler_respects_custom_settings(self):
        import numpy as np
        self.props.enabled = True

        # Default settings
        bpy.context.scene.frame_set(1)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        pixels_default = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_default)

        # Change contrast significantly
        self.props.contrast = 500
        # Invalidate CRT cache to pick up new settings
        addon_module._HandlerState.release_all()
        addon_module._ntsc_frame_handler(bpy.context.scene)
        pixels_high = np.zeros(len(img.pixels), dtype=np.float32)
        img.pixels.foreach_get(pixels_high)

        self.assertFalse(np.array_equal(pixels_default, pixels_high))

    def test_handler_skips_out_of_range_frame(self):
        self.props.enabled = True
        # Move to a frame outside the strip range
        bpy.context.scene.frame_set(9999)
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_handler_no_strip(self):
        _clear_sequencer()
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNone(img)

    def test_monochrome(self):
        self.props.as_color = False
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_progressive(self):
        self.props.progressive = True
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_no_scanlines_no_blend(self):
        self.props.scanlines = False
        self.props.blend = False
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_high_noise(self):
        self.props.noise = 200
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_offsets(self):
        self.props.xoffset = 20
        self.props.yoffset = -10
        self._enable_and_process()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)


# ===================================================================
# Test: Frame Handler (VHS)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestFrameHandlerVHS(unittest.TestCase):
    """Test the handler with ntscvhs system."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.props.system = "ntscvhs"
        self.props.num_frames = 1
        self.strip = _add_movie_strip(TEST_VIDEO)

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def test_vhs_basic(self):
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_vhs_with_aberration(self):
        self.props.enabled = True
        self.props.do_aberration = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)

    def test_vhs_cache_system(self):
        self.props.enabled = True
        addon_module._ntsc_frame_handler(bpy.context.scene)
        self.assertEqual(addon_module._HandlerState.crt_system, "ntscvhs")


# ===================================================================
# Test: Refresh Operator
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestRefreshOperator(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        _disable_handler()
        bpy.context.scene.frame_set(1)
        self.props = bpy.context.scene.ntsc_crt
        self.props.num_frames = 1
        self.props.enabled = True
        _add_movie_strip(TEST_VIDEO)

    def tearDown(self):
        _disable_handler()
        _clear_sequencer()
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        if img is not None:
            bpy.data.images.remove(img)

    def test_refresh_processes_frame(self):
        result = bpy.ops.sequencer.ntsc_refresh()
        self.assertIn("FINISHED", result)
        img = bpy.data.images.get(addon_module._HandlerState.preview_name)
        self.assertIsNotNone(img)


# ===================================================================
# Entry point
# ===================================================================

if __name__ == "__main__":
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = [argv[0]]

    unittest.main(argv=["test_addon"] + argv[1:], exit=False)
