"""Tests for the NTSC-CRT Blender addon.

Exercises addon registration, UI properties, helper functions, and the
actual NTSC-CRT operator (adding a movie strip, running the operator,
verifying the output strip appears).

Run inside Blender in background mode:
    NTSC_CRT_PATH=/path/to/NTSC-CRT/python \
    /path/to/blender --background --python test/test_addon.py

Requires test/test_input.mp4 (generated by test runner or manually).
"""

import os
import sys
import tempfile
import unittest

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_TEST_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_TEST_DIR, os.pardir))

_NTSC_CRT_PATH = os.environ.get("NTSC_CRT_PATH")
if not _NTSC_CRT_PATH:
    _NTSC_CRT_PATH = os.path.join(_REPO_ROOT, "python")

for _p in (_NTSC_CRT_PATH, os.path.join(_NTSC_CRT_PATH, "lib")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

_ADDON_DIR = os.path.join(_REPO_ROOT, "examples", "blender_addon")

import bpy
import importlib.util

# Force-load the addon module from the repo, not Blender's installed copy
_spec = importlib.util.spec_from_file_location(
    "ntsc_crt_addon", os.path.join(_ADDON_DIR, "main.py")
)
addon_module = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(addon_module)

TEST_VIDEO = os.path.join(_TEST_DIR, "test_input.mp4")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_registered():
    if not hasattr(bpy.types.Scene, "ntsc_crt"):
        addon_module.register()


def _clear_sequencer():
    """Remove all strips from the sequencer."""
    scene = bpy.context.scene
    if scene.sequence_editor is None:
        return
    _, strips = addon_module._get_strips(scene)
    for s in list(strips):
        strips.remove(s)


def _add_movie_strip(filepath, channel=1, frame_start=1):
    """Add a movie strip and make it active. Returns the strip."""
    scene = bpy.context.scene
    if scene.sequence_editor is None:
        scene.sequence_editor_create()
    _, strips = addon_module._get_strips(scene)
    strip = strips.new_movie(
        name="Test Video",
        filepath=filepath,
        channel=channel,
        frame_start=frame_start,
    )
    scene.sequence_editor.active_strip = strip
    return strip


# ===================================================================
# Test: Registration
# ===================================================================

class TestAddonRegistration(unittest.TestCase):

    def test_register(self):
        addon_module.register()
        self.assertTrue(hasattr(bpy.types.Scene, "ntsc_crt"))

    def test_unregister_and_reregister(self):
        _ensure_registered()
        addon_module.unregister()
        self.assertFalse(hasattr(bpy.types.Scene, "ntsc_crt"))
        addon_module.register()
        self.assertTrue(hasattr(bpy.types.Scene, "ntsc_crt"))


# ===================================================================
# Test: All Property Defaults
# ===================================================================

def _reset_props():
    """Reset all addon properties to their defaults."""
    props = bpy.context.scene.ntsc_crt
    props.system = "ntsc"
    props.hue = 0
    props.brightness = 0
    props.contrast = 180
    props.saturation = 10
    props.black_point = 0
    props.white_point = 100
    props.scanlines = True
    props.blend = True
    props.v_fac = 0
    props.noise = 24
    props.artifact_hue = 0
    props.num_frames = 4
    props.progressive = False
    props.raw = False
    props.as_color = True
    props.xoffset = 0
    props.yoffset = 0
    props.do_aberration = False
    props.output_directory = ""


class TestPropertyDefaults(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        self.props = bpy.context.scene.ntsc_crt

    def test_system(self):
        self.assertEqual(self.props.system, "ntsc")

    def test_monitor_defaults(self):
        self.assertEqual(self.props.hue, 0)
        self.assertEqual(self.props.brightness, 0)
        self.assertEqual(self.props.contrast, 180)
        self.assertEqual(self.props.saturation, 10)
        self.assertEqual(self.props.black_point, 0)
        self.assertEqual(self.props.white_point, 100)

    def test_display_defaults(self):
        self.assertTrue(self.props.scanlines)
        self.assertTrue(self.props.blend)
        self.assertEqual(self.props.v_fac, 0)

    def test_signal_defaults(self):
        self.assertEqual(self.props.noise, 24)
        self.assertEqual(self.props.artifact_hue, 0)
        self.assertEqual(self.props.num_frames, 4)
        self.assertFalse(self.props.progressive)
        self.assertFalse(self.props.raw)
        self.assertTrue(self.props.as_color)

    def test_offset_defaults(self):
        self.assertEqual(self.props.xoffset, 0)
        self.assertEqual(self.props.yoffset, 0)

    def test_vhs_defaults(self):
        self.assertFalse(self.props.do_aberration)

    def test_output_defaults(self):
        self.assertEqual(self.props.output_directory, "")


# ===================================================================
# Test: Property Read/Write
# ===================================================================

class TestPropertyReadWrite(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def setUp(self):
        _reset_props()
        self.props = bpy.context.scene.ntsc_crt

    def test_system_switch(self):
        self.props.system = "ntscvhs"
        self.assertEqual(self.props.system, "ntscvhs")
        self.props.system = "ntsc"
        self.assertEqual(self.props.system, "ntsc")

    def test_monitor_props(self):
        self.props.hue = -90
        self.props.brightness = 50
        self.props.contrast = 250
        self.props.saturation = 80
        self.props.black_point = -20
        self.props.white_point = 150
        self.assertEqual(self.props.hue, -90)
        self.assertEqual(self.props.brightness, 50)
        self.assertEqual(self.props.contrast, 250)
        self.assertEqual(self.props.saturation, 80)
        self.assertEqual(self.props.black_point, -20)
        self.assertEqual(self.props.white_point, 150)

    def test_display_props(self):
        self.props.scanlines = False
        self.props.blend = False
        self.props.v_fac = 42
        self.assertFalse(self.props.scanlines)
        self.assertFalse(self.props.blend)
        self.assertEqual(self.props.v_fac, 42)

    def test_signal_props(self):
        self.props.noise = 100
        self.props.artifact_hue = 180
        self.props.num_frames = 8
        self.props.progressive = True
        self.props.raw = True
        self.props.as_color = False
        self.assertEqual(self.props.noise, 100)
        self.assertEqual(self.props.artifact_hue, 180)
        self.assertEqual(self.props.num_frames, 8)
        self.assertTrue(self.props.progressive)
        self.assertTrue(self.props.raw)
        self.assertFalse(self.props.as_color)

    def test_offset_props(self):
        self.props.xoffset = 50
        self.props.yoffset = -30
        self.assertEqual(self.props.xoffset, 50)
        self.assertEqual(self.props.yoffset, -30)

    def test_vhs_props(self):
        self.props.do_aberration = True
        self.assertTrue(self.props.do_aberration)


# ===================================================================
# Test: Helper Functions
# ===================================================================

class TestHelpers(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def test_get_strips_empty(self):
        _clear_sequencer()
        sed, strips = addon_module._get_strips(bpy.context.scene)
        if sed is not None:
            self.assertEqual(len(list(strips)), 0)

    def test_active_movie_strip_none(self):
        _clear_sequencer()
        result = addon_module._active_movie_strip(bpy.context)
        self.assertIsNone(result)

    def test_output_path_same_dir(self):
        p = addon_module._output_path("/tmp/video.mp4", "", "ntsc")
        self.assertEqual(p, "/tmp/video_ntsc_ntsc.mp4")

    def test_output_path_vhs(self):
        p = addon_module._output_path("/tmp/video.mp4", "", "ntscvhs")
        self.assertEqual(p, "/tmp/video_ntsc_ntscvhs.mp4")

    def test_output_path_custom_dir(self):
        p = addon_module._output_path("/tmp/video.mp4", "/tmp/out", "ntsc")
        self.assertTrue(p.startswith("/tmp/out"))
        self.assertTrue(p.endswith("video_ntsc_ntsc.mp4"))


# ===================================================================
# Test: Operator Poll
# ===================================================================

class TestOperatorPoll(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        _ensure_registered()

    def test_poll_false_no_strip(self):
        _clear_sequencer()
        self.assertFalse(
            addon_module.SEQUENCER_OT_ntsc_apply.poll(bpy.context)
        )

    @unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
    def test_poll_true_with_movie_strip(self):
        _clear_sequencer()
        _add_movie_strip(TEST_VIDEO)
        self.assertTrue(
            addon_module.SEQUENCER_OT_ntsc_apply.poll(bpy.context)
        )
        _clear_sequencer()


# ===================================================================
# Test: Full Operator Execution (NTSC system)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestOperatorNTSC(unittest.TestCase):
    """Run the Apply NTSC-CRT operator on a real video strip."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()
        cls._tmpdir = tempfile.mkdtemp(prefix="ntsc_test_")

    def setUp(self):
        _clear_sequencer()
        _reset_props()
        props = bpy.context.scene.ntsc_crt
        props.num_frames = 1  # fast for testing
        props.output_directory = self._tmpdir

    def tearDown(self):
        _clear_sequencer()

    def _run_operator(self):
        """Add a movie strip and run the NTSC operator. Return result."""
        strip = _add_movie_strip(TEST_VIDEO)
        result = bpy.ops.sequencer.ntsc_apply()
        return result

    def test_operator_finished(self):
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_output_file_created(self):
        self._run_operator()
        expected = os.path.join(self._tmpdir, "test_input_ntsc_ntsc.mp4")
        self.assertTrue(
            os.path.isfile(expected),
            f"Output file not found: {expected}",
        )
        self.assertGreater(os.path.getsize(expected), 0)

    def test_output_strip_added(self):
        self._run_operator()
        _, strips = addon_module._get_strips(bpy.context.scene)
        ntsc_strips = [
            s for s in strips
            if s.type == "MOVIE" and s.name.startswith("NTSC ")
        ]
        self.assertEqual(len(ntsc_strips), 1)
        self.assertTrue(ntsc_strips[0].name.startswith("NTSC NTSC"))

    def test_output_strip_on_correct_channel(self):
        strip = _add_movie_strip(TEST_VIDEO, channel=3)
        bpy.ops.sequencer.ntsc_apply()
        _, strips = addon_module._get_strips(bpy.context.scene)
        ntsc_strips = [
            s for s in strips
            if s.type == "MOVIE" and s.name.startswith("NTSC ")
        ]
        self.assertEqual(len(ntsc_strips), 1)
        self.assertEqual(ntsc_strips[0].channel, 4)

    def test_output_strip_aligned_in_time(self):
        strip = _add_movie_strip(TEST_VIDEO, frame_start=10)
        bpy.ops.sequencer.ntsc_apply()
        _, strips = addon_module._get_strips(bpy.context.scene)
        ntsc_strips = [
            s for s in strips
            if s.type == "MOVIE" and s.name.startswith("NTSC ")
        ]
        self.assertEqual(ntsc_strips[0].frame_final_start, 10)

    def test_custom_monitor_settings(self):
        props = bpy.context.scene.ntsc_crt
        props.hue = 30
        props.contrast = 220
        props.saturation = 5
        props.brightness = 10
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_monochrome(self):
        bpy.context.scene.ntsc_crt.as_color = False
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_progressive_scan(self):
        bpy.context.scene.ntsc_crt.progressive = True
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_no_scanlines_no_blend(self):
        props = bpy.context.scene.ntsc_crt
        props.scanlines = False
        props.blend = False
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_high_noise(self):
        bpy.context.scene.ntsc_crt.noise = 200
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_offsets(self):
        props = bpy.context.scene.ntsc_crt
        props.xoffset = 20
        props.yoffset = -10
        result = self._run_operator()
        self.assertIn("FINISHED", result)

    def test_trimmed_strip(self):
        """Trimming a strip should only process the visible frames."""
        _clear_sequencer()
        strip = _add_movie_strip(TEST_VIDEO)
        # Original is 60 frames. Trim 10 from start and 10 from end = 40 visible.
        strip.frame_offset_start = 10
        strip.frame_offset_end = 10
        expected_duration = strip.frame_final_duration  # should be 40

        result = bpy.ops.sequencer.ntsc_apply()
        self.assertIn("FINISHED", result)

        # Check output video has only the trimmed number of frames
        import cv2
        out_path = os.path.join(self._tmpdir, "test_input_ntsc_ntsc.mp4")
        cap = cv2.VideoCapture(out_path)
        out_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        cap.release()
        self.assertEqual(out_frames, expected_duration)


# ===================================================================
# Test: Full Operator Execution (VHS system)
# ===================================================================

@unittest.skipUnless(os.path.isfile(TEST_VIDEO), "test_input.mp4 missing")
class TestOperatorVHS(unittest.TestCase):
    """Run the operator with ntscvhs system and aberration."""

    @classmethod
    def setUpClass(cls):
        _ensure_registered()
        cls._tmpdir = tempfile.mkdtemp(prefix="ntsc_vhs_test_")

    def setUp(self):
        _clear_sequencer()
        props = bpy.context.scene.ntsc_crt
        props.system = "ntscvhs"
        props.num_frames = 1
        props.output_directory = self._tmpdir
        props.do_aberration = False

    def tearDown(self):
        _clear_sequencer()

    def test_vhs_basic(self):
        _add_movie_strip(TEST_VIDEO)
        result = bpy.ops.sequencer.ntsc_apply()
        self.assertIn("FINISHED", result)

    def test_vhs_output_file(self):
        _add_movie_strip(TEST_VIDEO)
        bpy.ops.sequencer.ntsc_apply()
        expected = os.path.join(self._tmpdir, "test_input_ntsc_ntscvhs.mp4")
        self.assertTrue(os.path.isfile(expected))

    def test_vhs_strip_name(self):
        _add_movie_strip(TEST_VIDEO)
        bpy.ops.sequencer.ntsc_apply()
        _, strips = addon_module._get_strips(bpy.context.scene)
        ntsc_strips = [
            s for s in strips
            if s.type == "MOVIE" and s.name.startswith("NTSC ")
        ]
        self.assertEqual(len(ntsc_strips), 1)
        self.assertTrue(ntsc_strips[0].name.startswith("NTSC NTSCVHS"))

    def test_vhs_with_aberration(self):
        bpy.context.scene.ntsc_crt.do_aberration = True
        _add_movie_strip(TEST_VIDEO)
        result = bpy.ops.sequencer.ntsc_apply()
        self.assertIn("FINISHED", result)


# ===================================================================
# Entry point
# ===================================================================

if __name__ == "__main__":
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = [argv[0]]

    unittest.main(argv=["test_addon"] + argv[1:], exit=False)
